language: node_js
node_js:
- '0.12'
- 4
- 5
sudo: false
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: INAB5hMXOFOzLa3G5ii1ebRX2YBUq8AenFWaLrnjit8UcT93xM+IarNeQ94epHDfoWBcVXuq+Npx7Rt2dSawLk1GApxyqPohPz6JrWoTFVxO2cRmfeqcQQwXEhxlQtbopxMEazdM7tnZGNA6tBB/l7zDr3wfGDpSL8vfAGSnOPk=
  on:
    tags: true
